# Generated by Django 5.2.15 on 2026-07-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
